// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZEoZKjyuoh1ggiY4xkUFQxo6Bx6IbvtY',
    appId: '1:546635380848:web:edd85b069b0a6a84299cb5',
    messagingSenderId: '546635380848',
    projectId: 'manga-world-project',
    authDomain: 'manga-world-project.firebaseapp.com',
    storageBucket: 'manga-world-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy89Zznb489AX9zcd7HYBoACuXSzaEMkE',
    appId: '1:546635380848:android:f34f1373e0bb5f14299cb5',
    messagingSenderId: '546635380848',
    projectId: 'manga-world-project',
    storageBucket: 'manga-world-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiL9dX1sio9_OMfYpJT8Tjrv6my_u2LoA',
    appId: '1:546635380848:ios:36dc57ede82859fc299cb5',
    messagingSenderId: '546635380848',
    projectId: 'manga-world-project',
    storageBucket: 'manga-world-project.firebasestorage.app',
    iosBundleId: 'com.example.mangaParade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiL9dX1sio9_OMfYpJT8Tjrv6my_u2LoA',
    appId: '1:546635380848:ios:36dc57ede82859fc299cb5',
    messagingSenderId: '546635380848',
    projectId: 'manga-world-project',
    storageBucket: 'manga-world-project.firebasestorage.app',
    iosBundleId: 'com.example.mangaParade',
  );
}
